/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlertSeverity } from '../model/models';
import { VehicleAlert } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AlertsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Obtener alertas
     * 
     * @param vehicleId 
     * @param simulationId 
     * @param severity 
     */
    getAlerts(vehicleId?: number, simulationId?: number, severity?: AlertSeverity, extraHttpRequestParams?: any): Observable<Array<VehicleAlert>>;

}
