export * from './alerts.service';
import { AlertsService } from './alerts.service';
export * from './commands.service';
import { CommandsService } from './commands.service';
export * from './positions.service';
import { PositionsService } from './positions.service';
export * from './routes.service';
import { RoutesService } from './routes.service';
export * from './simulations.service';
import { SimulationsService } from './simulations.service';
export * from './telemetry.service';
import { TelemetryService } from './telemetry.service';
export * from './vehicles.service';
import { VehiclesService } from './vehicles.service';
export * from './warehouses.service';
import { WarehousesService } from './warehouses.service';
export const APIS = [AlertsService, CommandsService, PositionsService, RoutesService, SimulationsService, TelemetryService, VehiclesService, WarehousesService];
