export * from './alertController.service';
import { AlertControllerService } from './alertController.service';
export * from './comandos.service';
import { ComandosService } from './comandos.service';
export * from './routeController.service';
import { RouteControllerService } from './routeController.service';
export * from './simulationController.service';
import { SimulationControllerService } from './simulationController.service';
export * from './vehculos.service';
import { VehculosService } from './vehculos.service';
export * from './vehiclePositionController.service';
import { VehiclePositionControllerService } from './vehiclePositionController.service';
export * from './warehouseController.service';
import { WarehouseControllerService } from './warehouseController.service';
export const APIS = [AlertControllerService, ComandosService, RouteControllerService, SimulationControllerService, VehculosService, VehiclePositionControllerService, WarehouseControllerService];
