export * from './alerts.service';
import { AlertsService } from './alerts.service';
export * from './alerts.serviceInterface';
export * from './commands.service';
import { CommandsService } from './commands.service';
export * from './commands.serviceInterface';
export * from './positions.service';
import { PositionsService } from './positions.service';
export * from './positions.serviceInterface';
export * from './routes.service';
import { RoutesService } from './routes.service';
export * from './routes.serviceInterface';
export * from './simulations.service';
import { SimulationsService } from './simulations.service';
export * from './simulations.serviceInterface';
export * from './vehicles.service';
import { VehiclesService } from './vehicles.service';
export * from './vehicles.serviceInterface';
export * from './warehouses.service';
import { WarehousesService } from './warehouses.service';
export * from './warehouses.serviceInterface';
export const APIS = [AlertsService, CommandsService, PositionsService, RoutesService, SimulationsService, VehiclesService, WarehousesService];
