/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { VehicleCommand } from '../model/models';
import { VehicleCommandRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CommandsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Enviar comando a un vehículo
     * Envía un comando al vehículo.  El backend publicará el comando en Kafka. El simulador Python consumirá el evento y modificará el comportamiento del vehículo. 
     * @param vehicleId Identificador del vehículo
     * @param vehicleCommandRequest 
     */
    sendVehicleCommand(vehicleId: number, vehicleCommandRequest: VehicleCommandRequest, extraHttpRequestParams?: any): Observable<VehicleCommand>;

}
