/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { VehiclePosition } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PositionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Obtener posición actual del vehículo
     * 
     * @param vehicleId Identificador del vehículo
     */
    getVehiclePosition(vehicleId: number, extraHttpRequestParams?: any): Observable<VehiclePosition>;

}
