/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { CreateRouteRequest } from '../model/models';
import { Route } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoutesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear una ruta
     * Crea una ruta entre dos puntos. La ruta podrá ser calculada posteriormente mediante GraphHopper utilizando datos de OpenStreetMap. 
     * @param createRouteRequest 
     */
    createRoute(createRouteRequest: CreateRouteRequest, extraHttpRequestParams?: any): Observable<Route>;

    /**
     * Obtener ruta
     * 
     * @param routeId Identificador de la ruta
     */
    getRoute(routeId: number, extraHttpRequestParams?: any): Observable<Route>;

    /**
     * Obtener rutas
     * 
     */
    getRoutes(extraHttpRequestParams?: any): Observable<Array<Route>>;

}
