/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { CreateSimulationRequest } from '../model/models';
import { Simulation } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SimulationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear simulación
     * 
     * @param createSimulationRequest 
     */
    createSimulation(createSimulationRequest: CreateSimulationRequest, extraHttpRequestParams?: any): Observable<Simulation>;

    /**
     * Obtener simulación
     * 
     * @param simulationId Identificador de la simulación
     */
    getSimulation(simulationId: number, extraHttpRequestParams?: any): Observable<Simulation>;

    /**
     * Obtener simulaciones
     * 
     */
    getSimulations(extraHttpRequestParams?: any): Observable<Array<Simulation>>;

    /**
     * Pausar simulación
     * 
     * @param simulationId Identificador de la simulación
     */
    pauseSimulation(simulationId: number, extraHttpRequestParams?: any): Observable<Simulation>;

    /**
     * Reanudar simulación
     * 
     * @param simulationId Identificador de la simulación
     */
    resumeSimulation(simulationId: number, extraHttpRequestParams?: any): Observable<Simulation>;

    /**
     * Iniciar simulación
     * 
     * @param simulationId Identificador de la simulación
     */
    startSimulation(simulationId: number, extraHttpRequestParams?: any): Observable<Simulation>;

    /**
     * Detener simulación
     * 
     * @param simulationId Identificador de la simulación
     */
    stopSimulation(simulationId: number, extraHttpRequestParams?: any): Observable<Simulation>;

}
