/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { CreateVehicleRequest } from '../model/models';
import { UpdateVehicleRequest } from '../model/models';
import { Vehicle } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VehiclesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear vehículo
     * 
     * @param createVehicleRequest 
     */
    createVehicle(createVehicleRequest: CreateVehicleRequest, extraHttpRequestParams?: any): Observable<Vehicle>;

    /**
     * Eliminar vehículo
     * 
     * @param vehicleId Identificador del vehículo
     */
    deleteVehicle(vehicleId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Obtener vehículo
     * 
     * @param vehicleId Identificador del vehículo
     */
    getVehicle(vehicleId: number, extraHttpRequestParams?: any): Observable<Vehicle>;

    /**
     * Obtener vehículos
     * 
     */
    getVehicles(extraHttpRequestParams?: any): Observable<Array<Vehicle>>;

    /**
     * Actualizar vehículo
     * 
     * @param vehicleId Identificador del vehículo
     * @param updateVehicleRequest 
     */
    updateVehicle(vehicleId: number, updateVehicleRequest: UpdateVehicleRequest, extraHttpRequestParams?: any): Observable<Vehicle>;

}
