/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { CreateWarehouseRequest } from '../model/models';
import { UpdateWarehouseRequest } from '../model/models';
import { Warehouse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WarehousesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear almacén
     * 
     * @param createWarehouseRequest 
     */
    createWarehouse(createWarehouseRequest: CreateWarehouseRequest, extraHttpRequestParams?: any): Observable<Warehouse>;

    /**
     * Eliminar almacén
     * 
     * @param warehouseId Identificador del almacén
     */
    deleteWarehouse(warehouseId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Obtener almacén
     * 
     * @param warehouseId Identificador del almacén
     */
    getWarehouse(warehouseId: number, extraHttpRequestParams?: any): Observable<Warehouse>;

    /**
     * Obtener almacenes
     * 
     */
    getWarehouses(extraHttpRequestParams?: any): Observable<Array<Warehouse>>;

    /**
     * Actualizar almacén
     * 
     * @param warehouseId Identificador del almacén
     * @param updateWarehouseRequest 
     */
    updateWarehouse(warehouseId: number, updateWarehouseRequest: UpdateWarehouseRequest, extraHttpRequestParams?: any): Observable<Warehouse>;

}
