/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecargohub.backend.api;

import com.ecargohub.backend.api.model.AlertSeverity;
import com.ecargohub.backend.api.model.VehicleAlert;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-25T06:54:58.902000414Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Alerts", description = "Alertas generadas durante las simulaciones")
public interface AlertsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_GET_ALERTS = "/api/alerts";
    /**
     * GET /api/alerts : Obtener alertas
     *
     * @param vehicleId  (optional)
     * @param simulationId  (optional)
     * @param severity  (optional)
     * @return Lista de alertas (status code 200)
     */
    @Operation(
        operationId = "getAlerts",
        summary = "Obtener alertas",
        tags = { "Alerts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de alertas", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = VehicleAlert.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AlertsApi.PATH_GET_ALERTS,
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<VehicleAlert>> getAlerts(
        @Parameter(name = "vehicleId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "vehicleId", required = false) @Nullable Long vehicleId,
        @Parameter(name = "simulationId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "simulationId", required = false) @Nullable Long simulationId,
        @Parameter(name = "severity", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "severity", required = false) @Nullable AlertSeverity severity
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"severity\" : \"INFO\", \"id\" : 0, \"vehicleId\" : 6, \"speedLimit\" : 80, \"type\" : \"SPEED_LIMIT_EXCEEDED\", \"message\" : \"El vehículo supera el límite de velocidad.\", \"currentSpeed\" : 92, \"simulationId\" : 1, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"severity\" : \"INFO\", \"id\" : 0, \"vehicleId\" : 6, \"speedLimit\" : 80, \"type\" : \"SPEED_LIMIT_EXCEEDED\", \"message\" : \"El vehículo supera el límite de velocidad.\", \"currentSpeed\" : 92, \"simulationId\" : 1, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
