/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecargohub.backend.api;

import com.ecargohub.backend.api.model.ApiError;
import com.ecargohub.backend.api.model.VehicleCommand;
import com.ecargohub.backend.api.model.VehicleCommandRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-25T06:54:58.902000414Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Commands", description = "Comandos enviados a vehículos")
public interface CommandsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_SEND_VEHICLE_COMMAND = "/api/vehicles/{vehicleId}/commands";
    /**
     * POST /api/vehicles/{vehicleId}/commands : Enviar comando a un vehículo
     * Envía un comando al vehículo.  El backend publicará el comando en Kafka. El simulador Python consumirá el evento y modificará el comportamiento del vehículo. 
     *
     * @param vehicleId Identificador del vehículo (required)
     * @param vehicleCommandRequest  (required)
     * @return Comando aceptado (status code 202)
     *         or Petición incorrecta (status code 400)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "sendVehicleCommand",
        summary = "Enviar comando a un vehículo",
        description = "Envía un comando al vehículo.  El backend publicará el comando en Kafka. El simulador Python consumirá el evento y modificará el comportamiento del vehículo. ",
        tags = { "Commands" },
        responses = {
            @ApiResponse(responseCode = "202", description = "Comando aceptado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = VehicleCommand.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición incorrecta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CommandsApi.PATH_SEND_VEHICLE_COMMAND,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<VehicleCommand> sendVehicleCommand(
        @Min(1L) @Parameter(name = "vehicleId", description = "Identificador del vehículo", required = true, in = ParameterIn.PATH) @PathVariable("vehicleId") Long vehicleId,
        @Parameter(name = "VehicleCommandRequest", description = "", required = true) @Valid @RequestBody VehicleCommandRequest vehicleCommandRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"value\" : 1.4658129805029452, \"command\" : \"START\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
