/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecargohub.backend.api;

import com.ecargohub.backend.api.model.ApiError;
import com.ecargohub.backend.api.model.VehiclePosition;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-25T06:54:58.902000414Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Positions", description = "Posiciones de vehículos")
public interface PositionsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_GET_VEHICLE_POSITION = "/api/vehicles/{vehicleId}/position";
    /**
     * GET /api/vehicles/{vehicleId}/position : Obtener posición actual del vehículo
     *
     * @param vehicleId Identificador del vehículo (required)
     * @return Posición actual (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "getVehiclePosition",
        summary = "Obtener posición actual del vehículo",
        tags = { "Positions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Posición actual", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = VehiclePosition.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PositionsApi.PATH_GET_VEHICLE_POSITION,
        produces = { "application/json" }
    )
    
    default ResponseEntity<VehiclePosition> getVehiclePosition(
        @Min(1L) @Parameter(name = "vehicleId", description = "Identificador del vehículo", required = true, in = ParameterIn.PATH) @PathVariable("vehicleId") Long vehicleId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"acceleration\" : 0.8, \"heading\" : 274.2, \"latitude\" : 38.3452, \"vehicleId\" : 6, \"speedLimit\" : 90, \"speed\" : 92.5, \"longitude\" : -0.481, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
