/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecargohub.backend.api;

import com.ecargohub.backend.api.model.ApiError;
import com.ecargohub.backend.api.model.CreateRouteRequest;
import com.ecargohub.backend.api.model.Route;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-25T06:54:58.902000414Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Routes", description = "Gestión de rutas")
public interface RoutesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_CREATE_ROUTE = "/api/routes";
    /**
     * POST /api/routes : Crear una ruta
     * Crea una ruta entre dos puntos. La ruta podrá ser calculada posteriormente mediante GraphHopper utilizando datos de OpenStreetMap. 
     *
     * @param createRouteRequest  (required)
     * @return Ruta creada (status code 201)
     *         or Petición incorrecta (status code 400)
     */
    @Operation(
        operationId = "createRoute",
        summary = "Crear una ruta",
        description = "Crea una ruta entre dos puntos. La ruta podrá ser calculada posteriormente mediante GraphHopper utilizando datos de OpenStreetMap. ",
        tags = { "Routes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Ruta creada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Route.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición incorrecta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RoutesApi.PATH_CREATE_ROUTE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Route> createRoute(
        @Parameter(name = "CreateRouteRequest", description = "", required = true) @Valid @RequestBody CreateRouteRequest createRouteRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"distanceMeters\" : 425000, \"durationSeconds\" : 14400, \"origin\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"name\" : \"Alicante - Madrid\", \"destination\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"geometry\" : { \"coordinates\" : [ [ 6.027456183070403, 6.027456183070403 ], [ 6.027456183070403, 6.027456183070403 ] ], \"type\" : \"LineString\" }, \"id\" : 0, \"status\" : \"CREATED\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_ROUTE = "/api/routes/{routeId}";
    /**
     * GET /api/routes/{routeId} : Obtener ruta
     *
     * @param routeId Identificador de la ruta (required)
     * @return Ruta (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "getRoute",
        summary = "Obtener ruta",
        tags = { "Routes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ruta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Route.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RoutesApi.PATH_GET_ROUTE,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Route> getRoute(
        @Min(1L) @Parameter(name = "routeId", description = "Identificador de la ruta", required = true, in = ParameterIn.PATH) @PathVariable("routeId") Long routeId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"distanceMeters\" : 425000, \"durationSeconds\" : 14400, \"origin\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"name\" : \"Alicante - Madrid\", \"destination\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"geometry\" : { \"coordinates\" : [ [ 6.027456183070403, 6.027456183070403 ], [ 6.027456183070403, 6.027456183070403 ] ], \"type\" : \"LineString\" }, \"id\" : 0, \"status\" : \"CREATED\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_ROUTES = "/api/routes";
    /**
     * GET /api/routes : Obtener rutas
     *
     * @return Lista de rutas (status code 200)
     */
    @Operation(
        operationId = "getRoutes",
        summary = "Obtener rutas",
        tags = { "Routes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de rutas", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Route.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RoutesApi.PATH_GET_ROUTES,
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Route>> getRoutes(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"distanceMeters\" : 425000, \"durationSeconds\" : 14400, \"origin\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"name\" : \"Alicante - Madrid\", \"destination\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"geometry\" : { \"coordinates\" : [ [ 6.027456183070403, 6.027456183070403 ], [ 6.027456183070403, 6.027456183070403 ] ], \"type\" : \"LineString\" }, \"id\" : 0, \"status\" : \"CREATED\" }, { \"distanceMeters\" : 425000, \"durationSeconds\" : 14400, \"origin\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"name\" : \"Alicante - Madrid\", \"destination\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"geometry\" : { \"coordinates\" : [ [ 6.027456183070403, 6.027456183070403 ], [ 6.027456183070403, 6.027456183070403 ] ], \"type\" : \"LineString\" }, \"id\" : 0, \"status\" : \"CREATED\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
