/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecargohub.backend.api;

import com.ecargohub.backend.api.model.ApiError;
import com.ecargohub.backend.api.model.CreateSimulationRequest;
import com.ecargohub.backend.api.model.Simulation;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-25T06:54:58.902000414Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Simulations", description = "Gestión y control de simulaciones")
public interface SimulationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_CREATE_SIMULATION = "/api/simulations";
    /**
     * POST /api/simulations : Crear simulación
     *
     * @param createSimulationRequest  (required)
     * @return Simulación creada (status code 201)
     *         or Petición incorrecta (status code 400)
     */
    @Operation(
        operationId = "createSimulation",
        summary = "Crear simulación",
        tags = { "Simulations" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Simulación creada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Simulation.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición incorrecta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SimulationsApi.PATH_CREATE_SIMULATION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Simulation> createSimulation(
        @Parameter(name = "CreateSimulationRequest", description = "", required = true) @Valid @RequestBody CreateSimulationRequest createSimulationRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_SIMULATION = "/api/simulations/{simulationId}";
    /**
     * GET /api/simulations/{simulationId} : Obtener simulación
     *
     * @param simulationId Identificador de la simulación (required)
     * @return Simulación (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "getSimulation",
        summary = "Obtener simulación",
        tags = { "Simulations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Simulación", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Simulation.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SimulationsApi.PATH_GET_SIMULATION,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Simulation> getSimulation(
        @Min(1L) @Parameter(name = "simulationId", description = "Identificador de la simulación", required = true, in = ParameterIn.PATH) @PathVariable("simulationId") Long simulationId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_SIMULATIONS = "/api/simulations";
    /**
     * GET /api/simulations : Obtener simulaciones
     *
     * @return Lista de simulaciones (status code 200)
     */
    @Operation(
        operationId = "getSimulations",
        summary = "Obtener simulaciones",
        tags = { "Simulations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de simulaciones", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Simulation.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SimulationsApi.PATH_GET_SIMULATIONS,
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Simulation>> getSimulations(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_PAUSE_SIMULATION = "/api/simulations/{simulationId}/pause";
    /**
     * POST /api/simulations/{simulationId}/pause : Pausar simulación
     *
     * @param simulationId Identificador de la simulación (required)
     * @return Simulación pausada (status code 200)
     */
    @Operation(
        operationId = "pauseSimulation",
        summary = "Pausar simulación",
        tags = { "Simulations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Simulación pausada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Simulation.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SimulationsApi.PATH_PAUSE_SIMULATION,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Simulation> pauseSimulation(
        @Min(1L) @Parameter(name = "simulationId", description = "Identificador de la simulación", required = true, in = ParameterIn.PATH) @PathVariable("simulationId") Long simulationId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_RESUME_SIMULATION = "/api/simulations/{simulationId}/resume";
    /**
     * POST /api/simulations/{simulationId}/resume : Reanudar simulación
     *
     * @param simulationId Identificador de la simulación (required)
     * @return Simulación reanudada (status code 200)
     */
    @Operation(
        operationId = "resumeSimulation",
        summary = "Reanudar simulación",
        tags = { "Simulations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Simulación reanudada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Simulation.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SimulationsApi.PATH_RESUME_SIMULATION,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Simulation> resumeSimulation(
        @Min(1L) @Parameter(name = "simulationId", description = "Identificador de la simulación", required = true, in = ParameterIn.PATH) @PathVariable("simulationId") Long simulationId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_START_SIMULATION = "/api/simulations/{simulationId}/start";
    /**
     * POST /api/simulations/{simulationId}/start : Iniciar simulación
     *
     * @param simulationId Identificador de la simulación (required)
     * @return Simulación iniciada (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "startSimulation",
        summary = "Iniciar simulación",
        tags = { "Simulations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Simulación iniciada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Simulation.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SimulationsApi.PATH_START_SIMULATION,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Simulation> startSimulation(
        @Min(1L) @Parameter(name = "simulationId", description = "Identificador de la simulación", required = true, in = ParameterIn.PATH) @PathVariable("simulationId") Long simulationId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_STOP_SIMULATION = "/api/simulations/{simulationId}/stop";
    /**
     * POST /api/simulations/{simulationId}/stop : Detener simulación
     *
     * @param simulationId Identificador de la simulación (required)
     * @return Simulación detenida (status code 200)
     */
    @Operation(
        operationId = "stopSimulation",
        summary = "Detener simulación",
        tags = { "Simulations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Simulación detenida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Simulation.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SimulationsApi.PATH_STOP_SIMULATION,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Simulation> stopSimulation(
        @Min(1L) @Parameter(name = "simulationId", description = "Identificador de la simulación", required = true, in = ParameterIn.PATH) @PathVariable("simulationId") Long simulationId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"routeId\" : 1, \"name\" : \"Simulación Alicante-Madrid\", \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"vehicleId\" : 6, \"simulationSpeed\" : 1, \"status\" : \"CREATED\", \"finishedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
