/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecargohub.backend.api;

import com.ecargohub.backend.api.model.ApiError;
import com.ecargohub.backend.api.model.CreateVehicleRequest;
import com.ecargohub.backend.api.model.UpdateVehicleRequest;
import com.ecargohub.backend.api.model.Vehicle;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-25T06:54:58.902000414Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Vehicles", description = "Gestión de vehículos")
public interface VehiclesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_CREATE_VEHICLE = "/api/vehicles";
    /**
     * POST /api/vehicles : Crear vehículo
     *
     * @param createVehicleRequest  (required)
     * @return Vehículo creado (status code 201)
     *         or Petición incorrecta (status code 400)
     */
    @Operation(
        operationId = "createVehicle",
        summary = "Crear vehículo",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Vehículo creado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Vehicle.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición incorrecta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = VehiclesApi.PATH_CREATE_VEHICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Vehicle> createVehicle(
        @Parameter(name = "CreateVehicleRequest", description = "", required = true) @Valid @RequestBody CreateVehicleRequest createVehicleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currentPosition\" : { \"acceleration\" : 0.8, \"heading\" : 274.2, \"latitude\" : 38.3452, \"vehicleId\" : 6, \"speedLimit\" : 90, \"speed\" : 92.5, \"longitude\" : -0.481, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }, \"name\" : \"TRUCK-001\", \"id\" : 0, \"maxSpeed\" : 120, \"type\" : \"CAR\", \"status\" : \"IDLE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_DELETE_VEHICLE = "/api/vehicles/{vehicleId}";
    /**
     * DELETE /api/vehicles/{vehicleId} : Eliminar vehículo
     *
     * @param vehicleId Identificador del vehículo (required)
     * @return Vehículo eliminado (status code 204)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "deleteVehicle",
        summary = "Eliminar vehículo",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Vehículo eliminado"),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = VehiclesApi.PATH_DELETE_VEHICLE,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> deleteVehicle(
        @Min(1L) @Parameter(name = "vehicleId", description = "Identificador del vehículo", required = true, in = ParameterIn.PATH) @PathVariable("vehicleId") Long vehicleId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_VEHICLE = "/api/vehicles/{vehicleId}";
    /**
     * GET /api/vehicles/{vehicleId} : Obtener vehículo
     *
     * @param vehicleId Identificador del vehículo (required)
     * @return Vehículo (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "getVehicle",
        summary = "Obtener vehículo",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Vehículo", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Vehicle.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = VehiclesApi.PATH_GET_VEHICLE,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Vehicle> getVehicle(
        @Min(1L) @Parameter(name = "vehicleId", description = "Identificador del vehículo", required = true, in = ParameterIn.PATH) @PathVariable("vehicleId") Long vehicleId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currentPosition\" : { \"acceleration\" : 0.8, \"heading\" : 274.2, \"latitude\" : 38.3452, \"vehicleId\" : 6, \"speedLimit\" : 90, \"speed\" : 92.5, \"longitude\" : -0.481, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }, \"name\" : \"TRUCK-001\", \"id\" : 0, \"maxSpeed\" : 120, \"type\" : \"CAR\", \"status\" : \"IDLE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_VEHICLES = "/api/vehicles";
    /**
     * GET /api/vehicles : Obtener vehículos
     *
     * @return Lista de vehículos (status code 200)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getVehicles",
        summary = "Obtener vehículos",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de vehículos", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Vehicle.class)))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = VehiclesApi.PATH_GET_VEHICLES,
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Vehicle>> getVehicles(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"currentPosition\" : { \"acceleration\" : 0.8, \"heading\" : 274.2, \"latitude\" : 38.3452, \"vehicleId\" : 6, \"speedLimit\" : 90, \"speed\" : 92.5, \"longitude\" : -0.481, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }, \"name\" : \"TRUCK-001\", \"id\" : 0, \"maxSpeed\" : 120, \"type\" : \"CAR\", \"status\" : \"IDLE\" }, { \"currentPosition\" : { \"acceleration\" : 0.8, \"heading\" : 274.2, \"latitude\" : 38.3452, \"vehicleId\" : 6, \"speedLimit\" : 90, \"speed\" : 92.5, \"longitude\" : -0.481, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }, \"name\" : \"TRUCK-001\", \"id\" : 0, \"maxSpeed\" : 120, \"type\" : \"CAR\", \"status\" : \"IDLE\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_UPDATE_VEHICLE = "/api/vehicles/{vehicleId}";
    /**
     * PUT /api/vehicles/{vehicleId} : Actualizar vehículo
     *
     * @param vehicleId Identificador del vehículo (required)
     * @param updateVehicleRequest  (required)
     * @return Vehículo actualizado (status code 200)
     *         or Petición incorrecta (status code 400)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "updateVehicle",
        summary = "Actualizar vehículo",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Vehículo actualizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Vehicle.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición incorrecta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = VehiclesApi.PATH_UPDATE_VEHICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Vehicle> updateVehicle(
        @Min(1L) @Parameter(name = "vehicleId", description = "Identificador del vehículo", required = true, in = ParameterIn.PATH) @PathVariable("vehicleId") Long vehicleId,
        @Parameter(name = "UpdateVehicleRequest", description = "", required = true) @Valid @RequestBody UpdateVehicleRequest updateVehicleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currentPosition\" : { \"acceleration\" : 0.8, \"heading\" : 274.2, \"latitude\" : 38.3452, \"vehicleId\" : 6, \"speedLimit\" : 90, \"speed\" : 92.5, \"longitude\" : -0.481, \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }, \"name\" : \"TRUCK-001\", \"id\" : 0, \"maxSpeed\" : 120, \"type\" : \"CAR\", \"status\" : \"IDLE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
