/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecargohub.backend.api;

import com.ecargohub.backend.api.model.ApiError;
import com.ecargohub.backend.api.model.CreateWarehouseRequest;
import com.ecargohub.backend.api.model.UpdateWarehouseRequest;
import com.ecargohub.backend.api.model.Warehouse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-25T06:54:58.902000414Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Warehouses", description = "Gestión de almacenes")
public interface WarehousesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_CREATE_WAREHOUSE = "/api/warehouses";
    /**
     * POST /api/warehouses : Crear almacén
     *
     * @param createWarehouseRequest  (required)
     * @return Almacén creado (status code 201)
     *         or Petición incorrecta (status code 400)
     */
    @Operation(
        operationId = "createWarehouse",
        summary = "Crear almacén",
        tags = { "Warehouses" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Almacén creado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Warehouse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición incorrecta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = WarehousesApi.PATH_CREATE_WAREHOUSE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Warehouse> createWarehouse(
        @Parameter(name = "CreateWarehouseRequest", description = "", required = true) @Valid @RequestBody CreateWarehouseRequest createWarehouseRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : \"Avenida de Elche 25, Alicante\", \"name\" : \"Almacén Alicante\", \"location\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_DELETE_WAREHOUSE = "/api/warehouses/{warehouseId}";
    /**
     * DELETE /api/warehouses/{warehouseId} : Eliminar almacén
     *
     * @param warehouseId Identificador del almacén (required)
     * @return Almacén eliminado (status code 204)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "deleteWarehouse",
        summary = "Eliminar almacén",
        tags = { "Warehouses" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Almacén eliminado"),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = WarehousesApi.PATH_DELETE_WAREHOUSE,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> deleteWarehouse(
        @Min(1L) @Parameter(name = "warehouseId", description = "Identificador del almacén", required = true, in = ParameterIn.PATH) @PathVariable("warehouseId") Long warehouseId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_WAREHOUSE = "/api/warehouses/{warehouseId}";
    /**
     * GET /api/warehouses/{warehouseId} : Obtener almacén
     *
     * @param warehouseId Identificador del almacén (required)
     * @return Almacén (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "getWarehouse",
        summary = "Obtener almacén",
        tags = { "Warehouses" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Almacén", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Warehouse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WarehousesApi.PATH_GET_WAREHOUSE,
        produces = { "application/json" }
    )
    
    default ResponseEntity<Warehouse> getWarehouse(
        @Min(1L) @Parameter(name = "warehouseId", description = "Identificador del almacén", required = true, in = ParameterIn.PATH) @PathVariable("warehouseId") Long warehouseId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : \"Avenida de Elche 25, Alicante\", \"name\" : \"Almacén Alicante\", \"location\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_GET_WAREHOUSES = "/api/warehouses";
    /**
     * GET /api/warehouses : Obtener almacenes
     *
     * @return Lista de almacenes (status code 200)
     */
    @Operation(
        operationId = "getWarehouses",
        summary = "Obtener almacenes",
        tags = { "Warehouses" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de almacenes", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Warehouse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WarehousesApi.PATH_GET_WAREHOUSES,
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Warehouse>> getWarehouses(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"address\" : \"Avenida de Elche 25, Alicante\", \"name\" : \"Almacén Alicante\", \"location\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"id\" : 0 }, { \"address\" : \"Avenida de Elche 25, Alicante\", \"name\" : \"Almacén Alicante\", \"location\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"id\" : 0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_UPDATE_WAREHOUSE = "/api/warehouses/{warehouseId}";
    /**
     * PUT /api/warehouses/{warehouseId} : Actualizar almacén
     *
     * @param warehouseId Identificador del almacén (required)
     * @param updateWarehouseRequest  (required)
     * @return Almacén actualizado (status code 200)
     *         or Petición incorrecta (status code 400)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "updateWarehouse",
        summary = "Actualizar almacén",
        tags = { "Warehouses" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Almacén actualizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Warehouse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición incorrecta", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = WarehousesApi.PATH_UPDATE_WAREHOUSE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Warehouse> updateWarehouse(
        @Min(1L) @Parameter(name = "warehouseId", description = "Identificador del almacén", required = true, in = ParameterIn.PATH) @PathVariable("warehouseId") Long warehouseId,
        @Parameter(name = "UpdateWarehouseRequest", description = "", required = true) @Valid @RequestBody UpdateWarehouseRequest updateWarehouseRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : \"Avenida de Elche 25, Alicante\", \"name\" : \"Almacén Alicante\", \"location\" : { \"latitude\" : 38.3452, \"longitude\" : -0.481 }, \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/vehicles/10\", \"error\" : \"NOT_FOUND\", \"message\" : \"Vehicle not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 404 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
