/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AlertType = {
    SpeedLimitExceeded: 'SPEED_LIMIT_EXCEEDED',
    EmergencyBraking: 'EMERGENCY_BRAKING',
    VehicleStopped: 'VEHICLE_STOPPED',
    RouteDeviation: 'ROUTE_DEVIATION',
    CommunicationError: 'COMMUNICATION_ERROR',
    SimulationError: 'SIMULATION_ERROR'
} as const;
export type AlertType = typeof AlertType[keyof typeof AlertType];

