/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoPointDto } from './geoPointDto';


export interface CreateWarehouseRequest { 
    name: string;
    address?: string;
    location: GeoPointDto;
}

