/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleType } from './vehicleType';


export interface CreateVehicleRequest { 
    name: string;
    type: VehicleType;
    maxSpeed: number;
}
export namespace CreateVehicleRequest {
}


