/**
 * E-Cargo Hub API
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Comandos actualmente soportados por el backend
 */
export const ExecutableVehicleCommandType = {
    Start: 'START',
    Pause: 'PAUSE',
    Resume: 'RESUME',
    Stop: 'STOP',
} as const;
export type ExecutableVehicleCommandType = typeof ExecutableVehicleCommandType[keyof typeof ExecutableVehicleCommandType];

