/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Geometría de una ruta como una secuencia de coordenadas geográficas. 
 */
export interface GeoLineString { 
    type: GeoLineString.TypeEnum;
    coordinates: Array<Array<number>>;
}
export namespace GeoLineString {
    export const TypeEnum = {
        LineString: 'LineString'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


