/**
 * E-Cargo Hub API
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoLineString } from './geoLineString';
import { GeoPoint } from './geoPoint';
import { RouteStatus } from './routeStatus';


export interface Route { 
    id: number;
    name: string;
    origin: GeoPoint;
    destination: GeoPoint;
    distanceMeters?: number | null;
    durationSeconds?: number | null;
    status: RouteStatus;
    geometry?: GeoLineString | null;
}
export namespace Route {
}


