/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoLineString } from './geoLineString';
import { GeoPoint } from './geoPoint';
import { RouteStatus } from './routeStatus';


export interface Route { 
    id: number;
    name: string;
    origin: GeoPoint;
    destination: GeoPoint;
    distanceMeters: number;
    durationSeconds: number;
    status: RouteStatus;
    geometry?: GeoLineString;
}
export namespace Route {
}


