/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RouteStatus = {
    Created: 'CREATED',
    Calculating: 'CALCULATING',
    Ready: 'READY',
    Error: 'ERROR'
} as const;
export type RouteStatus = typeof RouteStatus[keyof typeof RouteStatus];

