/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoLineStringDto } from './geoLineStringDto';
import { GeoPointDto } from './geoPointDto';


export interface RouteDto { 
    id?: number;
    name?: string;
    origin?: GeoPointDto;
    destination?: GeoPointDto;
    distanceMeters?: number;
    durationSeconds?: number;
    status?: RouteDto.StatusEnum;
    geometry?: GeoLineStringDto;
}
export namespace RouteDto {
    export const StatusEnum = {
        Created: 'CREATED',
        Calculating: 'CALCULATING',
        Ready: 'READY',
        Error: 'ERROR',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


