/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationStatus } from './simulationStatus';


export interface Simulation { 
    id: number;
    name: string;
    vehicleId: number;
    routeId: number;
    status: SimulationStatus;
    startedAt?: string;
    finishedAt?: string;
    simulationSpeed?: number;
}
export namespace Simulation {
}


