/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SimulationStatus = {
    Created: 'CREATED',
    Running: 'RUNNING',
    Paused: 'PAUSED',
    Finished: 'FINISHED',
    Stopped: 'STOPPED',
    Error: 'ERROR'
} as const;
export type SimulationStatus = typeof SimulationStatus[keyof typeof SimulationStatus];

