/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulationDto { 
    id?: number;
    name?: string;
    vehicleId?: number;
    routeId?: number;
    status?: SimulationDto.StatusEnum;
    startedAt?: string;
    finishedAt?: string;
    simulationSpeed?: number;
}
export namespace SimulationDto {
    export const StatusEnum = {
        Created: 'CREATED',
        Running: 'RUNNING',
        Paused: 'PAUSED',
        Finished: 'FINISHED',
        Stopped: 'STOPPED',
        Error: 'ERROR',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


