/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Punto de telemetría registrado
 */
export interface TelemetryPointDto { 
    /**
     * ID interno
     */
    id?: number;
    /**
     * ID del vehículo
     */
    vehicleId?: number;
    /**
     * Latitud
     */
    latitude?: number;
    /**
     * Longitud
     */
    longitude?: number;
    /**
     * Progreso del trayecto (0-100)
     */
    progress?: number;
    /**
     * Velocidad en km/h
     */
    speedKmh?: number;
    /**
     * Estado del vehículo
     */
    status?: string;
    /**
     * Momento en que se registró
     */
    recordedAt?: string;
}

