/**
 * E-Cargo Hub API
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelemetryPoint { 
    id: number;
    vehicleId: number;
    latitude: number;
    longitude: number;
    progress: number;
    speedKmh: number;
    status: string;
    recordedAt: string;
}

