/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateVehicleRequest { 
    name: string;
    type: UpdateVehicleRequest.TypeEnum;
    maxSpeed: number;
}
export namespace UpdateVehicleRequest {
    export const TypeEnum = {
        Car: 'CAR',
        Van: 'VAN',
        Truck: 'TRUCK',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


