/**
 * E-Cargo Hub API
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutableVehicleCommandType } from './executableVehicleCommandType';


export interface VehicleCommandRequest { 
    command: ExecutableVehicleCommandType;
    /**
     * Valor asociado al comando. Por ejemplo, velocidad objetivo para SET_SPEED. 
     */
    value?: number | null;
    originLat?: number | null;
    originLon?: number | null;
    destLat?: number | null;
    destLon?: number | null;
}
export namespace VehicleCommandRequest {
}


