/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlertType } from './alertType';
import { AlertSeverity } from './alertSeverity';


export interface VehicleAlert { 
    id: number;
    vehicleId: number;
    simulationId?: number;
    type: AlertType;
    severity: AlertSeverity;
    message: string;
    currentSpeed?: number;
    speedLimit?: number;
    timestamp: string;
}
export namespace VehicleAlert {
}


