/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleCommandType } from './vehicleCommandType';


export interface VehicleCommand { 
    id: number;
    vehicleId: number;
    command: VehicleCommandType;
    value?: number;
    createdAt: string;
}
export namespace VehicleCommand {
}


