/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Estado actual de un vehículo
 */
export interface VehicleStatusDto { 
    /**
     * ID del vehículo
     */
    vehicleId?: number;
    /**
     * Latitud actual
     */
    latitude?: number;
    /**
     * Longitud actual
     */
    longitude?: number;
    /**
     * Progreso del trayecto (0-100)
     */
    progress?: number;
    /**
     * Velocidad actual en km/h
     */
    speedKmh?: number;
    /**
     * Estado actual del vehículo
     */
    status?: VehicleStatusDto.StatusEnum;
    /**
     * Última actualización
     */
    updatedAt?: string;
}
export namespace VehicleStatusDto {
    export const StatusEnum = {
        Idle: 'IDLE',
        EnRuta: 'EN_RUTA',
        Pausado: 'PAUSADO',
        Completado: 'COMPLETADO',
        Stopped: 'STOPPED',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


