/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const VehicleCommandType = {
    Start: 'START',
    Pause: 'PAUSE',
    Resume: 'RESUME',
    Stop: 'STOP',
    SetSpeed: 'SET_SPEED',
    IncreaseSpeed: 'INCREASE_SPEED',
    DecreaseSpeed: 'DECREASE_SPEED',
    EmergencyBrake: 'EMERGENCY_BRAKE'
} as const;
export type VehicleCommandType = typeof VehicleCommandType[keyof typeof VehicleCommandType];

