/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehiclePositionDto { 
    vehicleId?: number;
    latitude?: number;
    longitude?: number;
    speed?: number;
    speedLimit?: number;
    acceleration?: number;
    heading?: number;
    timestamp?: string;
}

