/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleCommandType } from './vehicleCommandType';


export interface VehicleCommandRequest { 
    command: VehicleCommandType;
    /**
     * Valor asociado al comando. Por ejemplo, velocidad objetivo para SET_SPEED. 
     */
    value?: number;
}
export namespace VehicleCommandRequest {
}


