/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehicleAlertDto { 
    id?: number;
    vehicleId?: number;
    simulationId?: number;
    type?: VehicleAlertDto.TypeEnum;
    severity?: VehicleAlertDto.SeverityEnum;
    message?: string;
    currentSpeed?: number;
    speedLimit?: number;
    timestamp?: string;
}
export namespace VehicleAlertDto {
    export const TypeEnum = {
        SpeedLimitExceeded: 'SPEED_LIMIT_EXCEEDED',
        EmergencyBraking: 'EMERGENCY_BRAKING',
        VehicleStopped: 'VEHICLE_STOPPED',
        RouteDeviation: 'ROUTE_DEVIATION',
        CommunicationError: 'COMMUNICATION_ERROR',
        SimulationError: 'SIMULATION_ERROR',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const SeverityEnum = {
        Info: 'INFO',
        Warning: 'WARNING',
        Critical: 'CRITICAL',
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
}


