/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Comando de vehículo persistido y publicado en Kafka
 */
export interface VehicleCommandDto { 
    /**
     * ID interno en BBDD
     */
    id?: number;
    /**
     * UUID único del comando (idempotencia)
     */
    commandId?: string;
    /**
     * ID del vehículo
     */
    vehicleId?: number;
    /**
     * Tipo de comando
     */
    command?: VehicleCommandDto.CommandEnum;
    /**
     * Valor asociado (opcional)
     */
    value?: number;
    /**
     * Latitud de origen (opcional)
     */
    originLat?: number;
    /**
     * Longitud de origen (opcional)
     */
    originLon?: number;
    /**
     * Latitud de destino (opcional)
     */
    destLat?: number;
    /**
     * Longitud de destino (opcional)
     */
    destLon?: number;
    /**
     * Fecha de creación (ISO-8601)
     */
    createdAt?: string;
}
export namespace VehicleCommandDto {
    export const CommandEnum = {
        Start: 'START',
        Pause: 'PAUSE',
        Resume: 'RESUME',
        Stop: 'STOP',
        SetSpeed: 'SET_SPEED',
        IncreaseSpeed: 'INCREASE_SPEED',
        DecreaseSpeed: 'DECREASE_SPEED',
        EmergencyBrake: 'EMERGENCY_BRAKE',
    } as const;
    export type CommandEnum = typeof CommandEnum[keyof typeof CommandEnum];
}


