/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehiclePositionDto } from './vehiclePositionDto';


export interface VehicleDto { 
    id?: number;
    name?: string;
    type?: VehicleDto.TypeEnum;
    maxSpeed?: number;
    status?: VehicleDto.StatusEnum;
    currentPosition?: VehiclePositionDto;
}
export namespace VehicleDto {
    export const TypeEnum = {
        Car: 'CAR',
        Van: 'VAN',
        Truck: 'TRUCK',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        Idle: 'IDLE',
        Running: 'RUNNING',
        Paused: 'PAUSED',
        Stopped: 'STOPPED',
        Error: 'ERROR',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


