/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const VehicleStatus = {
    Idle: 'IDLE',
    Running: 'RUNNING',
    Paused: 'PAUSED',
    Stopped: 'STOPPED',
    Error: 'ERROR'
} as const;
export type VehicleStatus = typeof VehicleStatus[keyof typeof VehicleStatus];

