/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const VehicleType = {
    Car: 'CAR',
    Van: 'VAN',
    Truck: 'TRUCK'
} as const;
export type VehicleType = typeof VehicleType[keyof typeof VehicleType];

