/**
 * E-Cargo Hub API
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleCommandType } from './vehicleCommandType';


export interface VehicleCommand { 
    id: number;
    commandId?: string | null;
    vehicleId: number;
    command: VehicleCommandType;
    value?: number | null;
    originLat?: number | null;
    originLon?: number | null;
    destLat?: number | null;
    destLon?: number | null;
    createdAt: string;
}
export namespace VehicleCommand {
}


