/**
 * Simulador Logístico
 *
 * Contact: admin@simulador-logistico.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoPoint } from './geoPoint';


export interface Warehouse { 
    id: number;
    name: string;
    address?: string;
    location: GeoPoint;
}

