spring:
  security:
    user:
      name: admin
      password: admin123

      
  application:
    name: E-Cargo-Hub

  datasource:
    url: jdbc:postgresql://localhost:5432/simulador_logistico
    username: simulador
    password: simulador
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    time-zone: UTC

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info