spring:
  application:
    name: E-Cargo-Hub

  security:
    user:
      name: admin
      password: admin123

  datasource:
    url: jdbc:postgresql://localhost:5432/simulador_logistico
    username: simulador
    password: simulador
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    time-zone: UTC

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:8085}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

graphhopper:
  api:
    key: ${GRAPHHOPPER_API_KEY:f9da97c3-e894-406e-823b-086ecd55b497}
    url: https://graphhopper.com/api/1

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info